# Generated by Django 5.1.4 on 2026-01-31 17:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('specialization', models.CharField(default='Кардиолог', max_length=100, verbose_name='Специализация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач')),
            ],
        ),
        migrations.CreateModel(
            name='ECGExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_file', models.FileField(upload_to='ecg_files/%Y/%m/%d/', verbose_name='Файл ЭКГ (.csv)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('hr', models.IntegerField(blank=True, null=True, verbose_name='ЧСС (уд/мин)')),
                ('qrs_duration', models.FloatField(blank=True, null=True, verbose_name='QRS (сек)')),
                ('p_duration', models.FloatField(blank=True, null=True, verbose_name='P (сек)')),
                ('pq_interval', models.FloatField(blank=True, null=True, verbose_name='PQ (сек)')),
                ('qt_interval', models.FloatField(blank=True, null=True, verbose_name='QT (сек)')),
                ('rhythm_type', models.CharField(default='Синусовый правильный', max_length=100, verbose_name='Ритм')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение врача')),
                ('ai_report_json', models.JSONField(blank=True, null=True, verbose_name='Отчет ИИ')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('healthy', 'Здоров'), ('pathology', 'Патология'), ('warning', 'Требует внимания')], default='pending', max_length=20, verbose_name='Статус ИИ')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Врач диагностики')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecgs', to='analyzer.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'ЭКГ Обследование',
                'ordering': ['-created_at'],
            },
        ),
    ]
